Presentation/Trialcar.Web/Controllers/DealerCarController.cs
using Incite.Core.Domain;
using Incite.Core.Infrastructure;
using Incite.Services;
using Incite.Services.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Trialcar.Web.Controllers
{
    [Authorize]
    public class DealerCarController : Controller
    {
        #region  Private Member Variables
        private readonly IDealerCarService _dealerCarService;
        private readonly IPaymentService _paymentService;
        #endregion

        #region Add car to compare
        public ActionResult AddToCompare()
        {
            dynamic showMessageString = string.Empty;
            try
            {

                System.Collections.Specialized.NameValueCollection nameValue = Request.Params;
                string dealerCarDetailId = nameValue.Get("dealerCarDetailId");
                System.Web.HttpContext context = System.Web.HttpContext.Current;
                DealerCarDetails carDetails = _dealerCarService.GetCarDetailById(int.Parse(dealerCarDetailId));

                if (carDetails.IsOnHold == false && carDetails.IsSold == false)
                {
                    if (context.Session["dealerCarDetailId"] == null)
                    {
                        //dealerIds[0] = dealerCarDetailId;
                        context.Session["dealerCarDetailId"] = dealerCarDetailId;
                        showMessageString = new
                        {
                            msg = "Add Car To Compare Successfully."
                        };
                    }
                    else
                    {
                        string carDetailSession = context.Session["dealerCarDetailId"].ToString();
                        string[] strCarDetailIds = carDetailSession.Split(',');
                        if (strCarDetailIds.Count() < 3)
                        {
                            context.Session["dealerCarDetailId"] = context.Session["dealerCarDetailId"] + "," + dealerCarDetailId;
                            showMessageString = new
                            {
                                msg = "Add Car To Compare Successfully."
                            };
                        }
                        else
                        {
                            showMessageString = new
                            {
                                err = "Maximum 3 Cars Compared."
                            };
                        }

                    }
                }
                else
                {
                    showMessageString = new
                    {
                        err = "Sold Cars and Cars On Hold Cannot Be Compared."
                    };
                }

            }
            catch (Exception e)
            {
                showMessageString = new
                {
                    err = "Problem While Adding Car To Compare."
                };
            }

            return Json(showMessageString, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Remove car from compare
        public ActionResult RemoveToCompare()
        {
            dynamic showMessageString = string.Empty;
            try
            {
                System.Collections.Specialized.NameValueCollection nameValue = Request.Params;
                string dealerCarDetailId = nameValue.Get("dealerCarDetailId");

                System.Web.HttpContext context = System.Web.HttpContext.Current;

                if (context.Session["dealerCarDetailId"] != null)
                {
                    string carDetailSession = context.Session["dealerCarDetailId"].ToString();
                    string[] strCarDetailIds = carDetailSession.Split(',');
                    if (strCarDetailIds.Contains(dealerCarDetailId))
                    {
                        var list = new List<string>(strCarDetailIds);
                        list.Remove(dealerCarDetailId);
                        strCarDetailIds = list.ToArray();
                    }
                    if (strCarDetailIds.Count() > 0)
                        context.Session["dealerCarDetailId"] = String.Join(",", strCarDetailIds);
                    else
                        context.Session["dealerCarDetailId"] = null;
                }
                showMessageString = new
                {
                    msg = "Remove Car From Compare Successfully."
                };
            }
            catch (Exception e)
            {
                showMessageString = new
                {
                    err = "Problem While Removing Car From Compare."
                };
            }

            return Json(showMessageString, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Car Compare
        public ActionResult Compare()
        {

            System.Web.HttpContext context = System.Web.HttpContext.Current;
            IList<DealerCarDetails> carList = new List<DealerCarDetails>();
            IList<CarAccessories> carAccessories = _dealerCarService.GetCarAccessories();

            if (context.Session["dealerCarDetailId"] != null)
            {
                string carDetailSession = context.Session["dealerCarDetailId"].ToString();
                string[] strCarDetailIds = carDetailSession.Split(',');

                foreach (string strId in strCarDetailIds)
                {
                    if (int.Parse(strId) > 0)
                    {
                        DealerCarDetails model = _dealerCarService.GetCarDetailById(int.Parse(strId));
                        carList.Add(model);
                    }
                }
            }

            return View(Tuple.Create(carList, carAccessories));
        }
        #endregion


        public DealerCarController(IDealerCarService DealerCarService, IPaymentService PaymentService)
        {
            _dealerCarService = DealerCarService;
            _paymentService = PaymentService;
        }
        // GET: DealerCar

        public ActionResult Index(DealerCarViewModel model = null)
        {
            return View(model);
        }

        #region Left Side Search Criteria
        public ActionResult MiniSearch(CarFilterViewModel args)
        {
            var model = _dealerCarService.PrepareDealarCarViewModel();
            return PartialView("_LeftSideSearchPanel", model);
        }

        #endregion

        #region Add and Update Car
        public ActionResult AddUpdateCar(string Cid)
        {
            int CId = 0;
            if (!string.IsNullOrEmpty(Cid))
                CId = int.Parse(EncryptDecryptHelper.Decrypt(Cid));
            var model = _dealerCarService.PrepareDealarCarViewModel(CId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddUpdateCar(DealerCarViewModel model)
        {
            model.AppUserId = Infrastructure.Authentication.CurrentUserId;
            var result = _dealerCarService.AddOrUpdateCar(model);

            return RedirectToAction("Index");
        }

        #endregion

        #region Delete Car Images

        [HttpPost]
        public ActionResult DeleteCarImage(string imageId)
        {
            ProcessViewModel resultmodel = new ProcessViewModel();
            resultmodel = _dealerCarService.DeleteCarImage(imageId);
            return new JsonResult() { Data = new { status = resultmodel.IsSuccess, message = resultmodel.Message }, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        #endregion


        #region Add or Update Dealer Car Comment        
        public ActionResult AddUpdateCarComment(DealerCommentNRatingViewModel dealerCommentVM)
        {
            dynamic showMessageString = string.Empty;
            if ((dealerCommentVM.Rating == 0) && (dealerCommentVM.Comment == null || dealerCommentVM.Comment.Trim() == ""))
            {
                showMessageString = new
                {
                    cls = "text-danger",
                    msg = "Please Rate or Comment."
                };
                return Json(showMessageString, JsonRequestBehavior.AllowGet);
            }
            else
            {
                dealerCommentVM.DealerId = Infrastructure.Authentication.CurrentUserId.Value;
                AppUsers ratingUser = _dealerCarService.addOrUpdateDealerCarComment(dealerCommentVM);

                float totRating = 0.0F, count = 0.0F;
                double avgRating = 0.0;
                int dealerCommentId = 0;

                if (ratingUser.DealerComments.Count > 0)
                {
                    foreach (var item in ratingUser.DealerComments)
                    {
                        totRating += item.Rating;
                        count++;

                    }
                    avgRating = Math.Round((totRating / count), 1);
                }

                if (dealerCommentVM.Id == 0)
                {
                    dealerCommentId = _dealerCarService.countDealerComments();

                    showMessageString = new
                    {
                        cls = "bg-success",
                        msg = "Rating done successfully.",
                        avgRatings = avgRating,
                        commentId = dealerCommentId
                    };
                }
                else
                {
                    showMessageString = new
                    {
                        cls = "bg-success",
                        msg = "Rating done successfully.",
                        avgRatings = avgRating
                    };
                }

                return Json(showMessageString, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region Add or Update Dealer Car Comment Reply      
        public ActionResult AddUpdateCarCommentReply(DealerCommentNRatingViewModel dealerCommentVM)
        {

Presentation/Trialcar.Web/Controllers/SearchController.cs
using Incite.Data.Repositories;
using Incite.Services;
using Incite.Services.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trialcar.Web.Helper;

namespace Trialcar.Web.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        #region  Private Member Variables
        private readonly IDealerCarService _DealerCarService;
        private readonly ICarSearchService _CarSearchService;
        #endregion
        #region ctor
        public SearchController(IDealerCarService dealerCarService, ICarSearchService carSearchService)
        {
            _DealerCarService = dealerCarService;
            _CarSearchService = carSearchService;
        }
        #endregion
        // GET: Search
        public ActionResult SearchResult()
        {
            return View();
        }
        [ChildActionOnly]
        public PartialViewResult HomeFilter()
        {
            var model = _CarSearchService.PrepareHomeCareFilter();
            return PartialView(model);
        }
        [ChildActionOnly]
        public PartialViewResult SearchLeftFilter(CarFilterViewModel request)
        {
            var model = _CarSearchService.PrepareHomeCareFilter(request);
            return PartialView(model);
        }
        [ChildActionOnly]
        public PartialViewResult MygarageLeftFilter(CarFilterViewModel request)
        {
            var model = _CarSearchService.PrepareHomeCareFilter(request);
            return PartialView(model);
        }
        [ChildActionOnly]
        public PartialViewResult CarlistSortBy(CarFilterViewModel request)
        {
            var model = _CarSearchService.PrepareSortby(request);
            return PartialView(model);
        }
        
    }
}

Presentation/Trialcar.Web/Controllers/SharedController.cs
using Incite.Services;
using Incite.Services.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Incite.Core.Domain;
using Incite.Core.Infrastructure;

namespace Trialcar.Web.Controllers
{
    [Authorize]
    public class SharedController : Controller
    {
        #region  Private Member Variables
        private readonly IDealerCarService _dealerCarService;
        private readonly IUsersService _userService;
        private readonly IPaymentService _paymentService;

        #endregion

        public SharedController(IUsersService usersService, IDealerCarService DealerCarService, IPaymentService paymentService)
        {
            _userService = usersService;
            _dealerCarService = DealerCarService;
            _paymentService = paymentService;
        }

       

        #region Car Listing
        public PartialViewResult CarListing(CarFilterViewModel args, bool IsDealerSearch, int dealerId = 0, bool IsSold = false, int Page = 1)
        {
            IPagedList<DealerCarDetails> lst = null;
            AppUsers appUsers = _dealerCarService.getUserById(dealerId);
            long currentUserId;
            if (dealerId > 0)
            {
                currentUserId = dealerId;
            } else
            {
                currentUserId = Infrastructure.Authentication.CurrentUserId ?? default(int);
            }

            ViewBag.IsPaymetList = true;
            var userProfile = _userService.GetUserProfile(Convert.ToInt32(currentUserId));
            var userpaymentList = _paymentService.GetUserPaymentSourceList(userProfile.User.Email);
            if(userpaymentList != null && userpaymentList.Data != null && userpaymentList.Count() > 0)
            {
                ViewBag.IsPaymetList = false;
            }
            


            var model = _dealerCarService.GetDealerCarListing(currentUserId, args, IsDealerSearch, IsSold);

            lst = model.ToPagedList(Page, (int)SiteEnum.PageSetting.PageSize);
            return PartialView("_CarListing", Tuple.Create(lst, appUsers));
        }
        #endregion
    }
}

Presentation/Trialcar.Web/Views/DealerCar/BuyNowHoldNowDetail.cshtml
@using Incite.Services.ViewModels
@model BuyNowHoldNowDetailViewModel

@{
    Layout = null;
}

@{

    Html.EnableClientValidation(true);
    Html.EnableUnobtrusiveJavaScript(true);
}

<div class="col-md-12 col-sm-6">
    <div id="dvLoginMsg" class="alert alert-info dvdismiss" style="display:none;">
    </div>
    @using (Html.BeginForm("BuyNowHoldNowDetail", "DealerCar",FormMethod.Post, new { id = "BuyNowHoldNowDetailForm" }))
    {

        @Html.AntiForgeryToken()


        <div class="col-md-12 col-sm-6">

            @Html.HiddenFor(m => m.DealerCarDetailId)
            @Html.HiddenFor(m => m.IsOnHold)

            @if (Model.PaymentTypes != null)
            {

                <div class="form-group">
                    <label for="example-email" class="col-md-12">Payment Mode</label>
                    @Html.DropDownListFor(m => m.PaymentTypeId
                      , new SelectList(Model.PaymentTypes, "Id", "PaymentType", Model.PayId)
                      , "Select Payment Mode"
                      , new { @id = "drpPayment", @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PaymentTypeId, string.Empty, new { @class = "text-danger" })
                </div>

            }
            <div class="raw form-group">
                <input type="button" onclick="buynowclick();"  value="Confirm"  name="bynowConfirm" class="btn btn-success"/>
            </div>
        </div>

    }
</div>






<script type="text/javascript">
    function buynowclick() {
        var fd = new FormData();
        var drppamentvalue = $("#drpPayment").val();
        var Delarcarid = $("#DealerCarDetailId").val();
        var ishold = $("#IsOnHold").val();
        if (drppamentvalue != "Select Payment Mode" && drppamentvalue != "" ) {
            fd.append("DealerCarDetailId", Delarcarid);
            fd.append("IsOnHold", ishold);
            fd.append("PaymentTypeId", drppamentvalue);
          
            $.ajax(
                {
                    
                    type: "POST",
                    url: "/Dealer/BuyNowHoldNowDetail",
                    data: fd,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        paymentsucess(data)
                    },
                    complete: function () {

                    }
                }
            );

        }
        else {
            alert("Select Payment Mode")
        }

    }
    function paymentsucess(data) {
        
        if (data.IsSuccess == true) {
            alert(data.Message);
            window.location.reload();
        }
        else {
            alert(data.Message);
        }
    }
</script>

Presentation/Trialcar.Web/Views/DealerCar/DealerDetail.cshtml
@model Incite.Core.Domain.AppUsers
@{
    ViewBag.Title = "Dealer Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--Display car comments-->
@Html.Partial("_DealerCarCommentPartial", Model)
<!--/Display car comments-->
<!--Listing-->
<section class="listing-page">
    <div class="container">
        <div class="row">
            <!--Listing-->
            @{Html.RenderAction("CarListing", "Shared", new { IsDealerSearch = true, dealerId = Model.Id });}
            <!-- Listing-->
            <!--Left Side Bar-->
            @{Html.RenderAction("SearchLeftFilter", "Search"); }
            <!--Left Side Bar-->
        </div>
    </div>
</section>
<!-- /Listing-->
@*Styles.Render("~/Assets/Trialcars/css/fxss-rate.css")
@Scripts.Render("~/Assets/Trialcars/js/fxss-rate-iconfont.js")
@Scripts.Render("~/Assets/Trialcars/js/fxss-rate.js")
@{
    float totRating = 0.0F, count = 0.0F;
    double avgRating = 0.0;
    if (Model.DealerComments.Count > 0)
    {
        foreach (var item in @Model.DealerComments)
        {
            totRating += item.Rating;
            count++;

        }
        avgRating = Math.Round((totRating / count), 1);
    }
}
<script>
    $(".rating-container").rate({
        length: 5,
        value: @avgRating,
        readonly: true,
        size: '30px',
        text: false
    });
</script>*@ 

Presentation/Trialcar.Web/Views/DealerCar/DealerSoldCar.cshtml
@model Incite.Services.ViewModels.DealerCarViewModel
@using Incite.Core.Extention
@using Incite.Core.Infrastructure
@{
    ViewBag.Title = "SearchResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--Page Header-->
<section class="page-header soldcar">
    <div class="container">
        <div class="page-header_wrap">
            <div class="page-heading">
                <h1>My Sold Car</h1>
            </div>
            <ul class="coustom-breadcrumb">
                <li><a href="@Url.RouteUrl("HomeIndex")">Home</a></li>
                <li>My Sold Car</li>
            </ul>
        </div>
    </div>
    <!-- Dark Overlay-->
    <div class="dark-overlay"></div>
</section>
<!-- /Page Header -->

<section class="listing-page">
    <div class="container">
        <div class="row">
            <div class="row form-group">
                <div class="col-sm-12 text-right">
                    @*<a href="/AddCarInGarage/" class="btn">Add Car</a>*@
                </div>
            </div>
            <!--Listing-->
            @{Html.RenderAction("CarListing", "Shared", new { IsDealerSearch = true, IsSold = true });}
            <!-- Listing-->
            <!--Left Side Bar-->
            @*@{Html.RenderAction("MygarageLeftFilter", "Search"); }*@
            <!--Left Side Bar-->
        </div>
    </div>
</section>

Presentation/Trialcar.Web/Views/DealerCar/Index.cshtml
@model Incite.Services.ViewModels.DealerCarViewModel
@using Incite.Core.Extention
@using Incite.Core.Infrastructure


@{
    ViewBag.Title = "SearchResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="listing-page">
    <div class="container">
        <div class="row">
            <div class="row form-group">
                <div class="col-sm-12 text-right">
                    <a href="/AddCarInGarage/" class="btn">Add Car</a>
                </div>
                <div class="col-sm-12 text-center" style="display:none">
                    <p style="color:red">Enter your KYC/Bank Information for your cars to be able to search/buy/hold/visible a car at lower rates</p>
                </div>
            </div>

            <!--Listing-->
            @{Html.RenderAction("CarListing", "Shared", new { IsDealerSearch = true, IsSold = false });}
            <!-- Listing-->
            <!--Left Side Bar-->
            @{Html.RenderAction("MygarageLeftFilter", "Search"); }
            <!--Left Side Bar-->

        </div>
    </div>
</section>

Presentation/Trialcar.Web/Views/DealerCar/Messages.cshtml
@model IList<Incite.Core.Domain.AppUsers>
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int currLoginUserId = Trialcar.Web.Infrastructure.Authentication.CurrentUserId.Value;
    //var activeUsers = new List<string>();
}
@Styles.Render("~/Content/css/messages.css")
<link href="~/Content/Trialcars/css/font-awesome.min.css" rel="stylesheet" />
@*@Styles.Render("~/Content/Trialcars/css/bootstrap.min.css")*@
@Styles.Render("~/Content/css/font-awesome.min.css")
<script src="@Url.Content("~/Content/js/jquery-3.3.1.js")"></script>
<script src="@Url.Content("~/Content/js/bootstrap.min.js")"></script>

<!--Page Header--> 
<section class="page-header compare_page">
    
    <div class="container">

        <div class="page-header_wrap">
            <div class="page-heading">
                <h1>Messages</h1>
            </div>
            <ul class="coustom-breadcrumb">
                <li><a href="@Url.RouteUrl("HomeIndex")">Home</a></li>
                <li>Messages</li>
            </ul>
        </div>
    </div>
    <!-- Dark Overlay-->
    <div class="dark-overlay"></div>
</section>
<!-- /Page Header -->
<section class="inner_pages">
    <div class="container">
        <div class="recent_heading text-center">
            <h4>Recent Chat</h4>
        </div>
        @if (Model.Count == 0)
        {
            <h5>No Recent Chat. Initiate your conversation from a car details page.</h5>
        }
        <div class="sidebar_message inbox_people text-center" id="users_listing_div">
            @*
            <div id="users" class="span2">
                <ul data-bind="foreach: users">
                    <li data-bind="click: setAsPrivateChat, css: { privateChatUser: isPrivateChatUser }">
                        <img src="/Assets/images/img_user_active.jpg" style="height:20px;width:20px">
                        &nbsp;<span data-bind="text: name"></span>
                    </li>
                </ul>
            </div>
            *@
            @foreach (var dealer in Model)
            {
                <div id="user_div_@dealer.UserName" class="message_user_div" onclick="populateMessages(@dealer.Id, this)">
                    <span name="@dealer.UserName" class="user_name_span"><img src="@Url.Content("/Assets/images/dealer-logo.jpg")" alt="User" class="user_image" />&nbsp;@dealer.UserName</span>
                </div>
                <div>&nbsp;</div>
            }
        </div>
        <div class="message_content">
            <div id="msg_content_div">&nbsp;</div>
            <div style="clear:both">&nbsp;</div>

        </div>
        <div class="send_msg_form_div right_input_text" id="send_msg_frm_div">
            <form id="frmSendMessage">
                <div class="msg_div">
                    <div style="display: flex;"><input type="text" id="msg_txt_usr" name="message" class="msg_text_div" autofocus><input type="button" id="msg_submit_btn" value="" class="msg_btn"></div>
                </div>
                @Html.Hidden("toDealerId")
                @Html.Hidden("fromAction", "PopulateMessages")
            </form>
        </div>
        <div style="clear:both">&nbsp;</div>
    </div>
</section>


<!--Reference the autogenerated SignalR hub script.
    <script src="/Scripts/jquery.signalR-2.1.1.js"></script>
    <script src="/signalr/hubs"></script>
-->
@Styles.Render("~/Assets/Trialcars/css/messages.css")

Presentation/Trialcar.Web/Views/DealerCar/PopulateMessages.cshtml
@model Tuple<Incite.Core.Domain.AppUsers, IList<Incite.Core.Domain.DealerMessages>>
@{
    Layout = null;
    int currLoginUserId = Trialcar.Web.Infrastructure.Authentication.CurrentUserId.Value;
    //string userName = "";
    bool isLastSender = false;
    string usrTimeTo = "~", usrTimeFrom = "~", altUsrNm = "~";

    string usrImg = "~";

}
<script type="text/javascript">
        $(document).ready(function () {

            $("#toDealerId").val(@Model.Item1.Id);
        });
</script>
@Html.Hidden("sender_uname", Model.Item1.UserName)
@Html.Hidden("sender_img_src", usrImg)
@Html.Hidden("sender_alt_txt", altUsrNm)
@foreach (var message in Model.Item2)
{

    if (message.FromDealerId == currLoginUserId)
    {

<div class="msg_right_div msg_top_div">
    <div class="msg_div right_msg">@message.Message</div>
    @if (usrTimeFrom != message.CreatedTs.ToShortTimeString())
    {
    <div class="float_right">@message.CreatedTs.ToShortDateString(),&nbsp;@message.CreatedTs.ToShortTimeString()</div>
    }
</div>
        usrTimeFrom = @message.CreatedTs.ToShortTimeString();
        isLastSender = false;
    }
    else
    {
        <div class="msg_left_div msg_top_div">
            @if (!isLastSender)
            {
            <div class="msg_img_div">
                <div class="disp_inline">&nbsp;</div>
                @if (usrImg != "")
                {
                    <img src="@Url.Content("/Assets/images/dealer-logo.jpg")" alt="User" class="user_image" />
                }
                else
                {
                    <div class="alt_usr_img">@altUsrNm</div>
                }
            </div>

            }
            else
            {
                <div class="float_left width50">&nbsp;</div>
            }
                <div class="disp_inline">
                    <div class="msg_div left_msg">@message.Message</div>
                    @if (usrTimeTo != message.CreatedTs.ToShortDateString())
                    {
                    <div>@*@message.fromDealer.UserName,*@&nbsp;@message.CreatedTs.ToShortDateString(),&nbsp;@message.CreatedTs.ToShortTimeString()</div>
                    }
                </div>
        </div>
        usrTimeTo = message.CreatedTs.ToShortDateString();
        isLastSender = true;
    }

}
@Html.Hidden("usrTimeTo", usrTimeTo)
@Html.Hidden("usrTimeFrom", usrTimeFrom)

Presentation/Trialcar.Web/Views/DealerCar/_AddDealerComment.cshtml
@model Incite.Services.ViewModels.DealerCommentNRatingViewModel

<div>
    @using (Ajax.BeginForm("AddUpdateCarComment", "DealerCar", new AjaxOptions { HttpMethod = "POST", OnSuccess = "addCommentSuccess", OnFailure = "alert('Error Occured while Rating.')" }))
    {
        @Html.HiddenFor(m => m.Rating, new { @id = "dealerCarRating" })
        @Html.HiddenFor(m => m.RatingForDealerId)
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.CommentReply)
        <!-- Rating Stars Box -->
        <div class='rating-stars'>
            <ul id='stars'>
                <li class='star' title='Poor' data-value='1'>
                    <i class='fa fa-star fa-fw'></i>
                </li>
                <li class='star' title='Fair' data-value='2'>
                    <i class='fa fa-star fa-fw'></i>
                </li>
                <li class='star' title='Good' data-value='3'>
                    <i class='fa fa-star fa-fw'></i>
                </li>
                <li class='star' title='Excellent' data-value='4'>
                    <i class='fa fa-star fa-fw'></i>
                </li>
                <li class='star' title='WOW!!!' data-value='5'>
                    <i class='fa fa-star fa-fw'></i>
                </li>
            </ul>
        </div>
        <div style="clear:both"></div>
        <div>
            <div class="div-float-left">@Html.TextAreaFor(m => m.Comment, new { @rows = 2, @class = "form-control" })</div>
            <div class="comm_btn_div"><input type="submit" class="commentbtn btn" value="Go!"></div>
        </div>
        <div style="clear:both"></div>
    }
    <!--Display Dealer Car Comments-->
    <span class="CarCommentResult"></span>
    <!--/Display Dealer Car Comments-->
</div>
    

Presentation/Trialcar.Web/Views/DealerCar/_AddDealerCommentReply.cshtml
@model Incite.Services.ViewModels.DealerCommentNRatingViewModel
@using (Ajax.BeginForm("AddUpdateCarCommentReply", "DealerCar", new AjaxOptions { HttpMethod = "POST", OnSuccess = "addCommentSuccess", OnFailure = "alert('Error Occured while Reply.')" }))
{
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.Comment)
    @Html.HiddenFor(m => m.Rating)
    @Html.HiddenFor(m => m.RatingForDealerId)
    @Html.HiddenFor(m => m.CreatedTs)

    <input type="hidden" name="DealerId" value="@Model.DealerId" />
    <div class="div-float-left">@Html.TextAreaFor(m => m.CommentReply, new { @rows = 2, @class = "form-control" })</div>
    <div class="comm_btn_div"><input type="submit" class="commentbtn btn" value="Reply"></div>
    <div style="clear:both"></div>
}
<!--Display Dealer Car Comments-->
<span class="CarCommentResult"></span>
<!--/Display Dealer Car Comments-->

Presentation/Trialcar.Web/Views/DealerCar/_UserImagePartial.cshtml
@model string
@{ string userImage = string.Empty; }
@if (Model != "")
{
    userImage = Model.TrimStart(new char[] { '~' });
    <div class="div-float-left"><img src="@userImage" asp-append-version="true" class="rating-usr-img" /></div>
}
else
{
    //userImage = "/Assets/images/default-user.png";
    <div class="div-float-left">
        <i class="fa fa-user-circle fa-3x" style=""></i>
    </div>
}